### ISSUE TITLE
使用Lambda表达式的问题

### ISSUE THREAD

**Issue by SkyFlyTang** [Blankj/RxBus#10]
package com.blankj.rxbus.demo;

import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.view.View;
import android.widget.TextView;

import com.blankj.rxbus.RxBus;

public class RxBusActivity extends AppCompatActivity {

    private TextView tvSticky;

    public static void start(Context context) {
        Intent starter = new Intent(context, RxBusActivity.class);
        context.startActivity(starter);
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        tvSticky = findViewById(R.id.tv_sticky);

        RxBus.getDefault().subscribe(this, (RxBus.Callback<String>) s -> {
            tvSticky.setText(Config.appendMsg("without " + s));
            throw new NullPointerException("");
        });

        RxBus.getDefault().subscribe(this, "my tag", (RxBus.Callback<String>) s -> tvSticky.setText(Config.appendMsg("with " + s)));

        RxBus.getDefault().subscribe(this, (RxBus.Callback<TestCallback>) testCallback -> tvSticky.setText(Config.appendMsg(testCallback.call())));
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        RxBus.getDefault().unregister(this);
    }

    public void postWithoutTag(View view) {
        Config.restoreMsg();
        RxBus.getDefault().post("tag");
    }

    public void postWithTag(View view) {
        Config.restoreMsg();
        RxBus.getDefault().post("tag", "my tag");
    }

    public void postStickyWithoutTag(View view) {
        Config.restoreMsg();
        RxBus.getDefault().postSticky("tag");
        StickyTestActivity.start(this);
    }

    public void postStickyWithTag(View view) {
        Config.restoreMsg();
        RxBus.getDefault().postSticky("tag", "my tag");
        StickyTestActivity.start(this);
    }

    public void useManager(View view) {
        RxBusManagerActivity.start(this);
        finish();
    }

    public void testInterface(View view) {
        Config.restoreMsg();
        for (int i = 0; i < 100; i++) {
            final int finalI = i;
            RxBus.getDefault().post((TestCallback) () -> String.valueOf(finalI));
        }
    }
}
报的错误
2018-09-14 00:57:27.291 9278-9278/com.blankj.rxbus.demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.blankj.rxbus.demo, PID: 9278
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.blankj.rxbus.demo/com.blankj.rxbus.demo.RxBusActivity}: java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
     Caused by: java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
        at com.blankj.rxbus.Utils.getTypeClassFromCallback(Utils.java:49)
        at com.blankj.rxbus.RxBus.subscribe(RxBus.java:125)
        at com.blankj.rxbus.RxBus.subscribe(RxBus.java:72)
        at com.blankj.rxbus.demo.RxBusActivity.onCreate(RxBusActivity.java:29)
        at android.app.Activity.performCreate(Activity.java:6662)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6077) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)

**Comment by SkyFlyTang** [comment]
这是根据你的例子吧java设置成java8,根据提示去转化成lambda,运行就报错，不信你可以去试试

**Comment by Blankj** [comment]
lambda 会消除范型，导致获取不到范型类型，建议 RxBus 相关代码不要使用 lambda 即可。

**Comment by Blankj** [comment]
最新 1.4 版本我把接口改成了抽象类来实现，这样在 Java 8 中就不能用 lambda 了，避免这种异常的出现。
