### ISSUE TITLE
在传递一个接口的时候会报空指针错误

### ISSUE THREAD

**Issue by qianshengta** [Blankj/RxBus#3]
```
public interface OnFragmentInteractionListener extends Serializable {
    void onFragmentInteraction(Bundle var1);
}
```
这是我的一个接口，我的MainFragment实现这个接口，然后传递出去
```
        // 发送带 tag 的 OnFragmentInteractionListener 类型事件
        RxBus.getDefault().postSticky(this, "MainFragment");
```
我的另外一个接口去接收这个数据
```
        // 注册带 tag  的 OnFragmentInteractionListener 类型事件
        RxBus.getDefault().subscribeSticky(this, "MainFragment", new RxBus
                .Callback<OnFragmentInteractionListener>() {
            @Override
            public void onEvent(OnFragmentInteractionListener listener) {

            }
        });
```
然后在接收的那个页面就报空指针了，以下是错误的log
  ```
 java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
                                                                                         at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:772)
                                                                                         at com.blankj.rxbus.CacheUtils.findStickyEvent(Unknown Source)
                                                                                         at com.blankj.rxbus.RxBus.subscribe(Unknown Source)
                                                                                         at com.blankj.rxbus.RxBus.subscribeSticky(Unknown Source)
                                                                                         at com.fubang.renewableresourcesclient.ui.home.BookingResultFragment.initParam(BookingResultFragment.java:61)
                                                                                         at com.qian.qianlibrary.base.fragment.BaseFragment.onResume(BaseFragment.java:104)
                                                                                         at android.support.v4.app.Fragment.performResume(Fragment.java:2390)
                                                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1474)
                                                                                         at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
                                                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
                                                                                         at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
                                                                                         at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
                                                                                         at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
                                                                                         at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
                                                                                         at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
                                                                                         at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
                                                                                         at android.os.Handler.handleCallback(Handler.java:743)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                         at android.os.Looper.loop(Looper.java:150)
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:5621)
                                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
```
我相同的代码，把传递的参数从OnFragmentInteractionListener改成String或其他的实体类(只要不是接口)，都是OK的，就是接口不行。我甚至可以在接收的时候直接接收这个MainFrament，然后转换成OnFragmentInteractionListener，但是就是不能以OnFragmentInteractionListener来接收

**Comment by Blankj** [comment]
事件是实体对象，不支持接口的，接口没有 hashcode，所以崩了

**Comment by qianshengta** [comment]
@Blankj 是的，我也找到解决办法了，直接传继承了这个接口的实体类，然后再强转成接口使用

**Comment by Blankj** [comment]
1.2 版本已支持接口了哈

**Comment by qianshengta** [comment]
收到
